---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default
resources:
  - ./base/pod.yml
  - ./base/rbac.yml

configMapGenerator:
- name: kube-event-alert
  namespace: default
  envs:
  - .env
