apiVersion: v1
kind: Pod
metadata:
  name: kube-event-alert
spec:
  containers:
  - image: ronenlib/kube-event-alert:1.0.1
    imagePullPolicy: Always
    name: kube-event-alert
    env:
      - name: WEBHOOK_URL
        valueFrom:
          configMapKeyRef:
            name: kube-event-alert
            key: webhook.url
  restartPolicy: Always
