name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  lint:
    name: Format
    runs-on: ubuntu-latest
    steps:

    - uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - uses: actions/checkout@v3

    - uses: golangci/golangci-lint-action@v3
      if: ${{ !env.ACT }}
      with:
        args: --timeout=3m --issues-exit-code=0 ./...

    - uses: golangci/golangci-lint-action@v3
      if: ${{ !env.ACT }}
      with:
        skip-cache: true
        args: --timeout=3m --issues-exit-code=0 ./...

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - uses: actions/checkout@v3

    - run: go test ./...

  build:
    needs:
      - lint
      - test
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - uses: actions/checkout@v3

    - run: go build -o kube-event-alert -v .
