---
name: k8s

on:
  pull_request

jobs:
  kustomize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: yokawasa/action-setup-kube-tools@v0.9.2
        with:
          setup-tools: |
            kustomize
            kubeconform

      - name: create fake .env file
        run: echo "webhook.url=https://example.org/webhook/123" > .env
        working-directory: k8s
      - run: kustomize build -o ./../kube-event-alert-deployment.yml .
        working-directory: k8s
      - run: cat kube-event-alert-deployment.yml
      - run: kubeconform -summary ./kube-event-alert-deployment.yml
